### ISSUE TITLE
Support regional flags

### ISSUE THREAD

**Issue by hsharrison** [cvzi/flag#4]
It would be nice if regional flags were supported with [tag sequences](http://unicode.org/reports/tr51/#valid-emoji-tag-sequences).

For example, `flag.flagize(':GB-ENG:')` would return `🏴gbeng✦` which would render as  
![image](https://user-images.githubusercontent.com/4441865/58812995-3a346380-8623-11e9-93a9-60609b240daf.png) when supported.

**Comment by cvzi** [comment]
Yeah I like it. 
It doesn't seem to be supported widely (yet) except for England's, Wales' and Scotland's flags, but on the other hand, it's no hard to implement. The system is very similar to how the other flags are encoded.

**Comment by cvzi** [comment]
Todo for version v1.1.0
- [ ] flagize() support
- [ ] dflagize() support
- [ ] Tests
- [ ] Explanation in readme and docs
- [ ] Example code in readme and docs
- [ ] List example flags in docs

**Comment by hsharrison** [comment]
Extremely fast from suggestion to implementation. Cheers!
