### ISSUE TITLE
Regional flags without dash

### ISSUE THREAD

**Issue by roguh** [cvzi/flag#5]
The Welsh flag could be [`":GBWLS:"`](https://emojipedia.org/flag-wales/) and the Scottish flag could be [`":GBSCT:"`](https://emojipedia.org/flag-scotland/).

This syntax is more true to the sequence of Latin Small Letters.

**Comment by cvzi** [comment]
The idea with the dash was that it does not match and convert stuff like `:heart:` or `:smile:`
The regular expression to find a regional flag in a text looks roughly like this: 
`:[a-zA-Z]{2}-[a-zA-Z]{1,4}:` and I don't like changing this.

I guess for some use cases, it would be nicer to have a function that converts just a single flag. That method could accept "anything" and just ignore the dash and colon. For example to get the flag of Wales all these could potentially work:
`singleflag(":GBWLS:")` 
`singleflag("GBWLS")`
`singleflag("gbwls")`
`singleflag("gb-wls")`
`...`

**Comment by roguh** [comment]
That makes sense! Thanks for the response and for your project.
